package com.example.ganknews.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.ganknews.gank.model.GankInfo;

import com.example.ganknews.db.GankInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gankInfoDaoConfig;

    private final GankInfoDao gankInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gankInfoDaoConfig = daoConfigMap.get(GankInfoDao.class).clone();
        gankInfoDaoConfig.initIdentityScope(type);

        gankInfoDao = new GankInfoDao(gankInfoDaoConfig, this);

        registerDao(GankInfo.class, gankInfoDao);
    }
    
    public void clear() {
        gankInfoDaoConfig.clearIdentityScope();
    }

    public GankInfoDao getGankInfoDao() {
        return gankInfoDao;
    }

}
